# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
# Tu respuesta aquí
nombre = "Santiago"
edad = 23
print("Hola, me llamo", nombre, "y tengo", edad, "años.")


Hola, me llamo Santiago y tengo 23 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [13]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
print("El primer numero es", numeros[0], "y el último es", numeros[5])
print("Los tres primeros son:", numeros[0:3])
numeros.append(99)
print(numeros)

El primer numero es 10 y el último es 15
Los tres primeros son: [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [14]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] > 6:
    print(estudiante["nombre"], "está aprobado.")
else:
    print(estudiante["nombre"], "está reprobado.")

Carlos está aprobado.


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [15]:
# Tu respuesta aquí
base = 5
altura = 8
Calcular_area =(base * altura) / 2
print("El área del triángulo es:", Calcular_area)

El área del triángulo es: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [16]:
# Tu respuesta aquí
cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [20]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [26]:
# Tu respuesta aquí
a = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo a:", a)
print( a.shape)
print(a.dtype)
print("-----------------")
print("-----------------")
b = np.zeros((3, 4))
print(b)
print("shape:", b.shape)
print("dtype:", b.dtype)
print("-----------------")
print("-----------------")
c = np.linspace(0, 1, 6)
print(c)
print("shape:", c.shape)
print("dtype:", c.dtype)


Arreglo a: [1.5 2.5 3.5 4.5]
(4,)
float64
-----------------
-----------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)
dtype: float64
-----------------
-----------------
[0.  0.2 0.4 0.6 0.8 1. ]
shape: (6,)
dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [29]:
a = np.arange(1, 13)

# Tu respuesta aquí

matriz = a.reshape(3, 4)

print("Matriz:")
print(matriz)

print("Valor máximo:", matriz.max())
print("Valor mínimo:", matriz.min())
print("Índice del máximo:", np.argmax(matriz))

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Valor máximo: 12
Valor mínimo: 1
Índice del máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [33]:
# Tu respuesta aquí
a = np.random.randint(1,21,5)
b = np.random.randint(1,21,5)

print(a)
print(b)
print("Operaciones:")

print(a + b)
print(a - b)
print(a * b)


[10  9  4  8  7]
[16 19 14 11  3]
Operaciones:
[26 28 18 19 10]
[ -6 -10 -10  -3   4]
[160 171  56  88  21]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [35]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
print(notas[notas >= 6])


[ 8.5  6.   9.2  7.8 10. ]
